### ISSUE TITLE
TUM human activity data domain ontology

### ISSUE THREAD

**Issue by daniel86** [ease-crc/soma#1]
This ticket is dedicated to discussing how we can proceed with generating NEEMs for the TUM human activity data.

The current plan is:
- have a closer look at the data, first concentrate on qualitative part (onto+tum)
- provide a domain ontology with fixed terminology (onto)
- use ontology terms for labelling (tum)
- later look into subsymbolic data

**Comment by daniel86** [comment]
the set of labels as provided by Karinne today.

[labels_TUM-ICS.zip](https://github.com/ease-crc/ease_ontology/files/2733126/labels_TUM-ICS.zip)

**Comment by daniel86** [comment]
@cuhde  from my first look I have two questions:
- Are "Flip", "Cut", "Pour" specializations of "ToolUse" ? Or what is it that defines "ToolUse"?
- "pancakeMix" is the tube that contains the mix I assume? Do you have a notion of stating that there is some sticky substance in the tube? e.g. what happens if there is not enough substance left such that a new tube needs to be opened?

**Comment by karinne-ics-tum** [comment]
@daniel86 You are right ToolUse is the general class of "flip", "cut" and "pour". Actually, these labels will be included in the ontology automatically, when these activities are inferred!
PancakeMix is the container of the dough. Right now, we do not have a notation to indicate that the container is full or empty. Any suggestions are more than welcome :)

**Comment by daniel86** [comment]
@karinne-ics-tum Hello! Sorry for the delay. We finally talked about the terms you provided in more detail.
Mainly one question remains: What is the difference between `Idle` and `StandingStill`?

We are now starting on preparing a TBox ontology for you. I will keep you updated

**Comment by karinne-ics-tum** [comment]
@daniel86 Hi, StandingStill means that there is no motion produced by the end-effector (hand). Idle, means that the hand is moving or not without a purpose. Does this makes sense to you?

**Comment by daniel86** [comment]
@karinne-ics-tum  is the distinction important for you?

**Comment by karinne-ics-tum** [comment]
@daniel86 Yes, it is important. As I mentioned before, they have different meanings :)

**Comment by daniel86** [comment]
From your description I do not see the importance because there is no relation to task-context in your mentioning. i.e. if you say that standing still is a goal of an activity,e.g. "stand still when someone makes a photo of you" -- then the distinction would make sense

**Comment by karinne-ics-tum** [comment]
Actually, we changed the label of "santingStill" to "Not Move". This motion is more abstract and the definition of Idle is the inferred one. We need both concepts.
Thanks :)
