### ISSUE TITLE
Joint-Hierarchy has SOMA-OBJ IRIs

### ISSUE THREAD

**Issue by shoeffner** [ease-crc/soma#139]
The Joint-Hierarchy still has SOMA-OBJ IRIs instead of the unified SOMA.

```
Joint
	FixedJoint
	MovableJoint
		FloatingJoint
		HingeJoint
			ContinuousJoint
			RevoluteJoint
		PlanarJoint
		PrismaticJoint
```

**Comment by daniel86** [comment]
that does not matter, as when we deploy, all IRIs are changed automatically to SOMA.owl

**Comment by shoeffner** [comment]
It does matter because that is in the deployed version.

**Comment by daniel86** [comment]
ohh you are right! actually the compile step in github CI should rename all IRIs. so some bug is there it seems
