### ISSUE TITLE
How to model "Steam"?

### ISSUE THREAD

**Issue by shoeffner** [ease-crc/soma#155]
I try to model Steam as a direct subClassOf Fluid and a meaningful description which states that steam is the product of the vaporization of water (which I also modeled as a separate Fluid).

My first approach was:
`hasPart some Water and isParticipantIn some Vaporizing`
However, this does not work as "Event DisjointWith Object".
Next I tried changing the isParticipantIn, so that I have:
`hasPart some Water and hasProcessType some Vaporizing`
The problem is that Vaporizing is a SocialObject while Steam is a PhysicalObject, eventually again coming down to "Event DisjointWith Object".

So I went to Vaporizing and checked its defintion:

```
isProcessTypeOf some 
    (AlteredObject
     and (classifies only Substance))
```

My AlteredObject would be Water.
The classified Substance should be Steam.

So I tried:
`Water and (isClassifiedBy Vaporizing)` (EventType DisjointWith Role)
and
`isProcessTypeOf some (Water and (isClassifiedBy Vaporizing))`  (EventType DisjointWith Role)
and
`hasProcessType some (Water and (isClassifiedBy Vaporizing))` (EventType DisjointWith Role)

So that doesn't work.

I went so far as to describe it as the constituent of something which matches the definition of Vaporization:
```
isConstituentOf some 
    (isProcessTypeOf some 
        (hasConstituent some Water 
        and (classifies some Fluid)
        )
    )
```

This is unsatisfying for several reasons: 
- the process I use to describe steam should classify Steam. Not "some Fluid" or "some Substance". But that would be circular.
- the AlteredObject IS Water, not something which has a constituent of Water
- As I do not directly use AlteredObject nor Vaporization, there is no way to "see" that this is in fact describing a product of a vaporization process. This is especially bad if at some point the Vaporization definition would change, as this definition would still follow the old one.

This all could equivalently be done with "Boiling" instead of Vaporization, but I went with the more general term.

What would be a better way to model Steam? Maybe something along the lines of an object properties which allows to assert that some objects are products of some processes?

I already use "isSourceOf" to state that a sink might be the source of water and a lamp the source of light, but that does not feel applicable here: "isSourceOf" might be very view-point dependent. For example, in my kitchen scenario there is steam coming out of a pot. To stop it from getting out, we might consider the pot as the source and close it with a lid. We could also consider the vaporization process as the source and turn off the heat to stop the water from boiling.

**Comment by daniel86** [comment]
We have this transient pattern, so you could say that the steam was created from some water that participated in an event that can be classified as Vaporizing.
That should be valid.

`transitionedFrom some (Water and isParticipantIn some (classifiedBy Vaporizing))`

**Comment by shoeffner** [comment]
Thanks, will try it out.

**Comment by mpomarlan** [comment]
`Water and (isClassifiedBy Vaporizing)` almost works, but as Protege says, Vaporizing is an EventType and if you want something to classify an object, that's a role. Working from the definition of Vaporizing (which, to be fair, does look weird to me now), this is more plausible:

`Water and (isClassifiedBy some (AlteredObject and (hasProcessType some Vaporizing)))`

**Comment by shoeffner** [comment]
Thanks, @mpomarlan's variant is working fine. I couldn't get "transitionedTo/From" to work.
