### ISSUE TITLE
Cup is missing from current SOMA

### ISSUE THREAD

**Issue by shoeffner** [ease-crc/soma#156]
This might be an issue with https://neemgit.informatik.uni-bremen.de/neems/ease-2020-pr2-setting-up-table, but the NEEM data there includes things labeled with http://www.ease-crc.org/ont/SOMA.owl#Cup which does not exist.

**Comment by daniel86** [comment]
https://ease-crc.github.io/soma/owl/current/SOMA-HOME.owl

SOMA-HOME includes this concept.
