### ISSUE TITLE
Inconsistency in LocatumRole and RelatumRole

### ISSUE THREAD

**Issue by shoeffner** [ease-crc/soma#170]
LocatumRole is defined as SubClass Of:
- classifies only PhysicalObject
- Role
- SpatialRelationRole

RelatumRole is defined as SubClass Of:
- classifies only PhysicalObject
- SpatialRelationRole

As the two are used in similar context, I think they either should both be direct subclasses of `Role`, or none of them should be. What do you think?

**Comment by daniel86** [comment]
@mpomarlan I would assume you created these definitions?

**Comment by daniel86** [comment]
should be fixed in #180
