### ISSUE TITLE
DependentPlace, Feature, and RelevantPart are all equivalent to owl:Nothing

### ISSUE THREAD

**Issue by shoeffner** [ease-crc/soma#171]
Here is the report for DependentPlace – as they seem to be related, it should be sufficient to only include these.

<img width="1805" alt="image" src="https://user-images.githubusercontent.com/1836815/106889498-5b96fe00-66e8-11eb-84b7-7289b7734de4.png">

SOMA version 1.1.0.

**Comment by mpomarlan** [comment]
This seems like it was solved, right? Perhaps can close.

**Comment by mrnolte** [comment]
I agree!
