### ISSUE TITLE
http://www.ease-crc.org/ont/SOMA-HOME.owl does not work

### ISSUE THREAD

**Issue by shoeffner** [ease-crc/soma#183]
http://www.ease-crc.org/ont/SOMA-HOME.owl does not redirect to https://ease-crc.github.io/soma/owl/current/SOMA-HOME.owl

**Comment by daniel86** [comment]
ah, you are right!
@sanic, could you help us?

**Comment by Sanic** [comment]
Done

**Comment by daniel86** [comment]
thanks @Sanic !
