### ISSUE TITLE
Latest DUL.owl (v34) does not work together with IOLite

### ISSUE THREAD

**Issue by daniel86** [ease-crc/soma#185]
DUL version v34pre is incompatible with IOLite.
SOMA applications need to use an earlier version to avoid inconsistencies.
This is the reason CI is reporting errors at the moment.

This version could be used:
http://www.ontologydesignpatterns.org/ont/dul/DUL_v32.owl

**Comment by daniel86** [comment]
@mpomarlan @shoeffner  any idea how we could force Hermit in CI to use specific DUL version?

**Comment by mpomarlan** [comment]
I think Hermit is just going to import whatever we point it to. Meaning, we'd probably have to change SOMA.owl

**Comment by daniel86** [comment]
e.g. owlapi would allow to do so: https://stackoverflow.com/questions/43155834/owl-api-v5-read-ontology-from-local-file

**Comment by shoeffner** [comment]
On my local build for [DLU](https://gitlab.informatik.uni-bremen.de/ease-ph/dlu/dlu), I pass all ontologies via the command line in "inheritance" order – but to be hones I am not 100% sure if it wouldn't try to get them from the web.

	java -jar org.semanticweb.hermit-x.x.x-jar-with-dependencies.jar --classify --classifyOPs --classifyDPs --output=inferences.txt resources/DUL.owl resources/IOLite.owl resources/SOMA.owl
