### ISSUE TITLE
Handling of changing qualities

### ISSUE THREAD

**Issue by sasjonge** [ease-crc/soma#190]
I want to give an object a quality that can change over time. Examples would be:

- An bottle of water is not empty at the moment (but could be empty later)
- An bottle of water is sealed or not sealed

I thought about using hasQuality, but this seems to be for permanent qualities of objects?

**Comment by mpomarlan** [comment]
As you suspect, ontologies in description logic are intended to be, just like mathematical relations among mathematical entities, "eternal". Something is what it is, forever. Something has a relationship to something else forever. Etc.

Obviously for us in the real world, this doesn't quite work, and various hacks have been developed. One of these which, AFAIK we use in SOMA, is "temporalized properties". The idea is that a statement receives an interval, within which it is true.

So you might have a "triple" asserting that a cup is red: {s=cup, p=hasColor, o=red}. To temporalize it, you would add a scope: {s=cup, p=hasColor, o=red, scope={start=<start timestamp>, end=<end timestamp>}}.

Protege does not support this, but KnowRob and openEASE should. Daniel can give you more info, but if you happen to look into the triples.json files inside NEEMs you will see this kind of scoping.
