### ISSUE TITLE
Hosting DUL ourselves

### ISSUE THREAD

**Issue by mrnolte** [ease-crc/soma#210]
Hi there,
It occurred repeatedly that DUL was not reachable via its IRI. Can we clone DUL and host it ourselves? This way we could also adjust unwanted definitions or concepts in DUL.

**Comment by mpomarlan** [comment]
I don't mind hosting it -- though so far I haven't had problems accessing it.

I would advise against adjusting it. To the extent that we wish to claim founding on DUL helps us connect to other ontologies of similar foundation, we should obey it as is and avoid schism.

**Comment by mpomarlan** [comment]
Further comment, just to make things "clearer": I'm quite fond of occasionally attempting to rewrite DUL in a lower formalism, e.g. EL++. So far though those would be personal hobby projects. A more serious decision would need a bit of politics as to how we position SOMA relative to what else is there in knowledge engineering.

**Comment by mrnolte** [comment]
Well, try aceessing DUL right now: http://www.ontologydesignpatterns.org/ont/dul/DUL.owl

**Comment by mpomarlan** [comment]
Oops so it is. The whole ontologydesignpatterns.org is down.

**Comment by mrnolte** [comment]
Yep. But I see your point not to change DUL; and while I agree with that, we sometimes understand and use Concepts and Relations not according to their original purpose. It might make things clearer. if we update the comments in DUL for those cases.

**Comment by mpomarlan** [comment]
Yes, that sounds quite useful.

**Comment by sasjonge** [comment]
This was implemented by

https://github.com/ease-crc/soma/pull/212
