### ISSUE TITLE
IOLite is still referenced in SOMA-SAY, SOMA-ACT and SOMA-IO

### ISSUE THREAD

**Issue by sasjonge** [ease-crc/soma#213]
IOLite is still referenced in several subontologies

SOMA-SAY:
https://github.com/ease-crc/soma/blob/56dc55dd9987ed6bb58b58fa462cc9361c9dd698/owl/SOMA-SAY.owl#L233

SOMA-ACT:
https://github.com/ease-crc/soma/blob/d3401bfa2fb573d5dc62d779fd706b86ae1e4a41/owl/SOMA-ACT.owl#L324

I think we agreed to remove SOMA-IO, but the changes for SOMA-SAY and ACT have to be discussed.

**Comment by mrnolte** [comment]
This is also an error due to `Formal Language` being made equivalent to `owl:Nothing`
