### ISSUE TITLE
Versionize SOMA

### ISSUE THREAD

**Issue by mrnolte** [ease-crc/soma#215]
We should make use of the OWL feature to versionize ontologies, so people can use stable versions. When making Updates to SOMA, we can then also write Changelogs.

**Comment by mrnolte** [comment]
When a new release is ready, we should automatically upload it etc., see here @sasjonge : https://trstringer.com/github-actions-create-release-upload-artifacts/

**Comment by mrnolte** [comment]
Also, this seems cool for an automatic changelog: https://mokkapps.de/blog/how-to-automatically-generate-a-helpful-changelog-from-your-git-commit-messages/

**Comment by mrnolte** [comment]
Has been discussed in todays meeting as should-be-done.

**Comment by sasjonge** [comment]
Solved, as discussed.

**Comment by daniel86** [comment]
as said in the meeting. versioned releases were done since quite a while now. only the mirroring on the ease-crc.org website is missing

**Comment by daniel86** [comment]
@mrnolte where do you want the versioned artifacts anyways?
They are surely allready available, e.g. here 
https://ease-crc.github.io/soma/owl/1.1.0/SOMA.owl

You also want them under ease-crc.org in a versioned URL? like that:
https://ease-crc.org/ont/1.2.0/SOMA.owl

The link is only there for the latest unreleased version at the moment, here
https://ease-crc.org/ont/SOMA.owl

**Comment by daniel86** [comment]
Well ok. the text of this ticket does not state anything about the modules, but ok.
@sasjonge you are looking into also deploying the modules, right? Please also have a look into rewriting the imports.

**Comment by sasjonge** [comment]
I created a PR were I changed the import links for the published modules for the release:
https://github.com/ease-crc/soma/pull/244
@mrnolte Is this the way how the modules should look like?

**Comment by sasjonge** [comment]
I merged https://github.com/ease-crc/soma/pull/244

This means we have a versioned release for 1.2.0, but the import structure of the modules is not automatically resolved for now.

**Comment by sasjonge** [comment]
This issue is fixed with the merge of https://github.com/ease-crc/soma/pull/244

I created a new issue for automatically changing the import URIs, here: https://github.com/ease-crc/soma/issues/246
