### ISSUE TITLE
Add isDefinedIn *everywhere*

### ISSUE THREAD

**Issue by mrnolte** [ease-crc/soma#218]
For development using multiple files, it is really cumbersome to find out which ontology file defines which concept, role, or even axiom.
It would be very helpful, to add isDefinedIn annotations automatically to all of those specifying their respective ontology, e.g., via CI.

**Comment by mrnolte** [comment]
Has been discussed in todays meeting as should-be-done.

**Comment by sasjonge** [comment]
This was resolved by https://github.com/ease-crc/soma/pull/260
