### ISSUE TITLE
Update DUL annotations

### ISSUE THREAD

**Issue by mrnolte** [ease-crc/soma#221]
DUL contains several problematic annotations:

- It is nice, that most concepts etc. are annotated with `rdfs:isDefinedIn`, some are however not. The missing annotations should be added
- I believe that some DUL designers configured their Protégé to automatically add them as authors of concepts and also the date when something was added to the ontology. This is unnecessary and should be deleted
- DUL is missing some labels. For example, `includesWhole` has no label. The missing labels should be added. Also see #208 .
- DUL sometimes includes italien labels in addition to the english ones. Unfortunately, sometimes these are preferred vs. the english ones in Protege - e.g., Protege displays insieme instead of set, which is not nice when searching through the taxonomy interface. We need to delete all italien labels to prevent this.

**Comment by sasjonge** [comment]
This was fixed by 

https://github.com/ease-crc/soma/pull/222
