### ISSUE TITLE
New Release before removal of IOLight

### ISSUE THREAD

**Issue by mrnolte** [ease-crc/soma#225]
Can we create a new release for the commit right before removal of IOLight? This way, we have a point in time from where we can start keeping track of changes (see also #215 )

**Comment by mrnolte** [comment]
So the release should be of Version 1bc185627e56ead510086c8c92c7f34003cb6906

**Comment by daniel86** [comment]
I will look into it

**Comment by daniel86** [comment]
here is the release: https://github.com/ease-crc/soma/releases/tag/1.2.0
