### ISSUE TITLE
Unintuitive axioms

### ISSUE THREAD

**Issue by mrnolte** [ease-crc/soma#236]
In SOMA ACT, we have, e.g., the following axiom:
```owl
hasInitialSituation some NonmanifestedSituation SubClassOf owl:Nothing
```
`hasInitialSituation` currently has the range `Situation`.
The above axiom could be expressed by changing that range to `Situation and not NonmanifestedSituation`.
This would have the advantage that one can directly see this restriction when inspecting `hasInitialSituation` - otherwise, one has to look at the usages or at owl:Nothing.

A similar axiom can be refactored for `hasTerminalSituation`.

**Comment by mpomarlan** [comment]
Counterpoint, the axiom as written is in EL++.

While SOMA as a whole is quite far from EL++, if at any point I will want to simplify it I would prefer to have as many of its axioms already in that fragment as possible.

**Comment by mrnolte** [comment]
That argument seems arbitrary to me. Why do it here when this is considered nowhere else in SOMA? E.g., we use nominals, oneOf, symmetric and asymmetric roles, union and more. There is no hope to capture the rich semantics of SOMA in OWL EL.

**Comment by mpomarlan** [comment]
In this particular case, the argument is I can't rewrite everything in DUL, nor everything else in SOMA -- but what I do add I prefer to write as EL++ if possible.

**Comment by mrnolte** [comment]
Usually, in these cases, projects tend to introduce two distinct ontologies, one full and one light. I guess we currently do not have the ressources to do that, though.
