### ISSUE TITLE
OntoMetrics and Webvowl not working with version 1.2.0 and current version

### ISSUE THREAD

**Issue by sasjonge** [ease-crc/soma#251]
OntoMetrics is still not working. It seems to work fine if I test it with the domain-ontologies but failes with the collapsed variant.

**Comment by sasjonge** [comment]
I found out that Ontometrics, as well as Webvowl are not working with version 1.2.0 and higher. 1.1.0 is working. I will update the title of this issue accordingly.

**Comment by sasjonge** [comment]
Update: I found out that removing all owl:Axioms that contain http://www.w3.org/2002/07/owl#Nothing

For example:

https://github.com/ease-crc/soma/blob/897a702b35dbe3c038ef5f213d71b1e3cd65b56f/owl/current/SOMA.owl#L5776

**Comment by mrnolte** [comment]
> Update: I found out that removing all owl:Axioms that contain http://www.w3.org/2002/07/owl#Nothing
> 
> For example:
> 
> https://github.com/ease-crc/soma/blob/897a702b35dbe3c038ef5f213d71b1e3cd65b56f/owl/current/SOMA.owl#L5776

What happens if you remove those axioms? You haven't stated that 😅

**Comment by sasjonge** [comment]
If i remove them, then Ontometrics and Webvowl are working correctly.

**Comment by sasjonge** [comment]
I created an issue in the WebVOWL repository:

https://github.com/VisualDataWeb/WebVOWL/issues/191

**Comment by mrnolte** [comment]
Is this now fixed (on our side)?

**Comment by sasjonge** [comment]
Yes, it is atleast fixed in the sense that the ontologies work with both services. I have to add Ontometrics back, because some changes are necessary.
