### ISSUE TITLE
Collapsed versions have wrong header

### ISSUE THREAD

**Issue by sasjonge** [ease-crc/soma#261]
The collapsed version of SOMA and SOMA-HOME are slightly broken in their header. 

For the SOMA file we have a wrong URI, it uses 

`<rdf:RDF xml:base="http://www.ease-crc.org/ont/SOMA-All.owl">`

instead of

`<rdf:RDF xml:base="http://www.ease-crc.org/ont/SOMA.owl">`

also the import of DUL seems to be missing in both files. See for example:

https://ease-crc.github.io/soma/owl/current/SOMA.owl

**Comment by sasjonge** [comment]
@mrnolte Could you fix the Java code? The CI part should work

**Comment by mrnolte** [comment]
Why should there be a DUL import in the collapsed verisons? Isn't that the point of the collapsed verisons, to make them loadable without imports?

**Comment by mrnolte** [comment]
Also, I do not see a difference between the to URIs that you posted above

**Comment by sasjonge** [comment]
Our old versions didn't have this, see

https://ease-crc.github.io/soma/owl/1.2.0/SOMA.owl

I think the point of the collapsed versions was to have a "deliverable" of our work (with the modules just being a way to modularize the work). DUL is not part of our work, and should be imported.

Do I see this correctly @mpomarlan @daniel86 ?

**Comment by sasjonge** [comment]
> Also, I do not see a difference between the two URIs that you posted above

I fixed my comment

**Comment by daniel86** [comment]
@sasjonge yes this seems reasonable. also currently KnowRob loads different ontology files into different named graphs in the database. also you would have a problem with the meta information of DUL.owl (or just loose it).

**Comment by sasjonge** [comment]
I think the merge was a bit early, the URI is still broken. Now it is

`https://ease-crc.github.io/soma/owl/current/SOMA.owl`

instead of

`http://www.ease-crc.org/ont/SOMA.owl`

See

https://github.com/ease-crc/soma/blob/gh-pages/owl/current/SOMA.owl

**Comment by mrnolte** [comment]
Fixed by #263

**Comment by mrnolte** [comment]
> I think the merge was a bit early, the URI is still broken. Now it is
> 
> `https://ease-crc.github.io/soma/owl/current/SOMA.owl`
> 
> instead of
> 
> `http://www.ease-crc.org/ont/SOMA.owl`
> 
> See
> 
> https://github.com/ease-crc/soma/blob/gh-pages/owl/current/SOMA.owl

That is easy to fix, just change the yaml

**Comment by sasjonge** [comment]
Fixed by https://github.com/ease-crc/soma/pull/266
