### ISSUE TITLE
Python's `owlready2` can't (properly) read the owl files

### ISSUE THREAD

**Issue by JeremiasThun** [ease-crc/soma#296]
The Python module for working with owl files, `owlready2`, doesn't seem to be able to read the uploaded OWL functional syntax. When loading the soma owl files (`onto = get_ontology("/Users/***/soma/owl/SOMA-OBJ")`), it returns the error

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/owlready2/driver.py", line 154, in parse
    s,p,o = splitter.split(line[:-3], 2)
ValueError: not enough values to unpack (expected 3, got 2)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/owlready2/namespace.py", line 1086, in load
    try:     new_base_iri = self.graph.parse(fileobj, default_base = self._orig_base_iri, **args)
  File "/usr/local/lib/python3.10/site-packages/owlready2/driver.py", line 188, in parse
    raise OwlReadyOntologyParsingError("NTriples parsing error (or unrecognized file format) in %s, line %s." % (getattr(f, "name", getattr(f, "url", "???")), current_line)) from e
owlready2.base.OwlReadyOntologyParsingError: NTriples parsing error (or unrecognized file format) in /Users/***/soma/owl/SOMA-OBJ.owl, line 9.
```

This can be avoided by exporting the same owl file to RDF XML Syntax (I used Protege to do that). But reading this file with `owlready2` and then saving the unchanged ontology with `onto.save("mynewfile.owl", format="rdfxml"` returns an owl file, that can't be properly read by protege, as you can see in the resulting class hierarchy:

<img width="623" alt="image" src="https://user-images.githubusercontent.com/32883765/210594208-5dbf33be-038a-4dd7-bdad-f89bd01f79c4.png">

**Comment by mrnolte** [comment]
I do not believe that this is an Issue of our ontology, but of owlready2 and / or protege. Maybe open an issue there ;)
