### ISSUE TITLE
Cleanup Quality branch

### ISSUE THREAD

**Issue by mpomarlan** [ease-crc/soma#83]
(As before, several discussion points lumped into one ticket to avoid spam)

1) Taxonomies of qualities. At the moment, this is less of a problem than in the Region section, but I can imagine that, as we add more Qualities, the various categories such as Extrinsic or Intrinsic will become more heterogeneous. This is starting to become an issue for Intrinsic, in my opinion, where Capacity and DeviceState are siblings. Something to think about then would be whether we should prepare some other groupings of qualities, e.g. on physical or geometric grounds.

2) Taxonomies of Dispositions. The same comments as above apply to Dispositions. At the moment, there is not too much obviously wrong, but as we add more Dispositions there is a danger the category will look more like a dumping ground than an organization. The fact that we have a Variability class is good, but we should perhaps consider what superclass might link various other functional qualities such as blockage or containment.

3) Refactoring of disposition names. While not elegant, sometimes just saying XDisposition is easier on the eyes. I had no idea what Deposition is supposed to mean until I read the comment. One can expect comments to be necessary to truly understand a concept, but knowing at a glance that we have a SupportDisposition is imo an improvement we could make. Same goes for names like Enclosure or Insertion, which very likely are names we will like to use elsewhere too.

4) Is Insertion (or InsertionDisposition) the right name to use? I agree that the word can mean many things, including placing something inside a container. However, it can also mean that some part of an object is inserted into a receptacle on another, often for assembly purposes, and the containment relation is not what is salient. If someone reads an instruction to "insert tab A (of board 1) into slot B (of panel 2)", and then we ask them whether the board or panel contains the other piece, I think most people will say No. They might say Yes to "does slot B contain tab A", but I wonder whether this containment relation is that salient or important.

5) Connectivity is a very overloaded word, and not a lot of that load is Disposition-related either.

**Comment by ayden175** [comment]
What is the state here? Have some of the points already been adressed?
