### ISSUE TITLE
Representing Slicing Actions

### ISSUE THREAD

**Issue by joserochh** [ease-crc/soma#94]
We were discussing on what could be a good fit to represent slicing actions:

EASE-ACT.owl#Actuating          focus more in the movement of the object
EASE-ACT.owl#Manipulating    focus more in the movement of the hand
Or rather if there should be a special class for it?

Slicing could be thought, for example, on how you manipulate a knife to achieve a cutting. Or how the knife is acted to achieve the cutting, specially because a blade can cut without being manipulated. Maybe in the specific example of slicing something with your hand both Actuating and Manipulating are involved.

**Comment by mpomarlan** [comment]
Hi!

This is an interesting case indeed. One can argue that the important thing about such an action isn't that it is performed by hand (as a manipulation would) or that it involves moving an object outside of the agent (as actuation would), but its effect on some other object. Specifically, slicing is that which, at least partially, transforms something into slices; it may involve a tool.

We have some other kinds of actions (or tasks) defined in our ontology, and in particular ModifyingPhysicalObject seems like a good superclass for Slicing.

At the moment, some of us from the onto dev team are on holiday for a few days, so expect this to not be done tomorrow, but I'll open a pull request to fix this in the beginning of next week.
